version: '3.9'
services:
  localDb:
    container_name: localDbContainer
    image: mysql:8
    env_file:
      - .env
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=password --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 30s
      retries: 15

  testDB:
    container_name: testDbContainer
    image: mysql:8
    env_file:
      - .env
    restart: always
    ports:
      - ${TEST_DATABASE_PORT}:${TEST_DATABASE_PORT}
    volumes:
      - ./.docker/mysql:/var/lib/mysqlTest
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${TEST_DATABASE_PORT}
    depends_on:
      localDb:
        condition: service_healthy
